---
- name: wired.network 
  template:
    src: 20-wired.network.j2
    dest: /etc/systemd/network/20-wired.network
    backup: true
    mode: 0644
  become: yes

- name: restart networking
  service:
    name: systemd-networkd 
    masked: no
    state: restarted
  become: yes

- name: rc.local
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    backup: true
  become: yes

- name: restart rclocal
  shell: "sh /etc/rc.local"
  become: yes

- name: disable wait online service
  service:
    name: systemd-networkd-wait-online 
    masked: yes
    state: stopped 
  become: yes


