# bridge_device_network_interface: the network interface that connects to your system
# bridge_wireless_network_interface: The network interface which connects to the RMF network
# bridge_device_ip: The ip address of your target device, with respect to the pi bridge
# bridge_dns: The nameserver that your device will contact for DNS resolution
---
bridge_device_network_interface: eth0              
bridge_upstream_network_interface: wlan0          
bridge_device_ip: 10.42.0.1                
bridge_dns: 8.8.8.8   

