# Role: ROS2
---
ros2_gpg_key_url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc            
ros2_repository_url: http://packages.ros.org/ros2/ubuntu
ros2_distribution: foxy
ros2_rmw_implementation: rmw_cyclonedds_cpp          
ros2_domain_id: 99
ros2_installation_type: ros-base
ros2_cycloneddsxml_path: "/etc"
ros2_dds_network_interface: wg0           

# unicast_cyclonedds
unicast_cyclonedds_max_auto_participant_index: 50             
unicast_cyclonedds_dds_network_interface: wg0             
unicast_cyclonedds_dds_ip: 10.0.0.2
unicast_cyclonedds_cycloneddsxml_path: "/etc"
unicast_cyclonedds_group_name: "unicast_cyclonedds_peers"

# wg_client
wg_client_wireguard_workspace_path: "/home/ubuntu/wireguard_ws"          
wg_client_wireguard_subnet: 24                                            
wg_client_wireguard_network_port: 51820
wg_client_wireguard_network_interface: wg0
wg_client_external_dns: 8.8.8.8
wg_client_wireguard_path: "/etc/wireguard"                               
wg_client_client_wireguard_ip: 10.0.0.2
wg_client_server_name: server_0
wg_client_server_wireguard_ip: 10.0.0.1                
wg_client_wireguard_allowed_ips: 10.0.0.0/24           
wg_client_has_systemctl: true

# bridge
bridge_device_network_interface: eth0              
bridge_upstream_network_interface: wlan0          
bridge_device_ip: 10.42.0.1                
bridge_dns: 8.8.8.8   

