- name: Update aptitude
  apt:
    upgrade: full
  become: true

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - ntpdate
      - ntp
  become: true

- name: stop ntp
  shell: timedatectl set-ntp off
  become: true

- name: Add time server
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ ntp_client_ntp_server_ip }} prefer iburst"
  become: yes

- name: start ntp
  service:
    name: ntp
    masked: no 
    state: restarted 
    enabled: yes
  become: yes


